### ISSUE TITLE
Unavalilable PLSuperExpCutoff2

### ISSUE THREAD

**Issue by FurutaT** [fermi-lat/modelEditor#2]
I used ModelEditor and I 'm said that 
TypeError: Invalid Spectrum type (PLSuperExpCutoff2)!
I avoid this problem by using text editor, but I would be happy if you fixed it.

(fermi) [furuta@hozuki first]$ conda list fermi
 packages in environment at /home/furuta/anaconda3/envs/fermi:

 Name                    Version                   Build  Channel
fermitools                1.0.7            py27h39e3cac_0    fermi
fermitools-data           0.17                          0    fermi

ModelEditor
(fermi) [furuta@hozuki first]$ ModelEditor model.xml 
/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/pyds9.py:94: UserWarning: Can't locate DS9 executable. Please add the DS9 directory to your PATH and try again.
  warnings.warn(ds9_warning)
Traceback (most recent call last):
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/ModelEditor.py", line 759, in <module>
    modelEditor = ModelEditorApp(root, path)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/ModelEditor.py", line 63, in __init__
    sourceLibraryDocument = SourceLibraryDocument(path = path)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/SourceLibraryDocument.py", line 60, in __init__
    self.fromFile(path)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/SourceLibraryDocument.py", line 350, in fromFile
    self.fromDom(dom)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/SourceLibraryDocument.py", line 219, in fromDom
    sourceLibrary = SourceLibrary(dom = sourceLibraryElement)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/SourceLibrary.py", line 77, in __init__
    self.fromDom(dom)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/SourceLibrary.py", line 163, in fromDom
    dom.getElementsByTagName('source')]
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/Source.py", line 104, in __init__
    self.fromDom(dom)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/Source.py", line 197, in fromDom
    spectrum = Spectrum(dom = domSpectrum)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/Spectrum.py", line 478, in __init__
    self.fromDom(dom)
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/Spectrum.py", line 557, in fromDom
    self.setType(dom.getAttribute('type'))
  File "/home/furuta/anaconda3/envs/fermi/lib/python2.7/site-packages/fermitools/Spectrum.py", line 608, in setType
    raise TypeError, 'Invalid Spectrum type (%s)!' % type
TypeError: Invalid Spectrum type (PLSuperExpCutoff2)!

**Comment by dagorym** [comment]
@FurutaT , could you attach the file you are trying to read in so I can use it for testing?  Thanks.

**Comment by FurutaT** [comment]
Thanks you for your reply. I attached file to read.
I changed filename from model.xml to model.txt when attached
[model.txt](https://github.com/fermi-lat/modelEditor/files/3375631/model.txt)


2019年7月10日(水) 4:34 Tom Stephens <notifications@github.com>:

**Comment by FurutaT** [comment]
[model.txt](https://github.com/fermi-lat/modelEditor/files/3375630/model.txt)

**Comment by dagorym** [comment]
This has been resolved with PR #3 and will appear in an upcoming release of the tools.

**Comment by jasercion** [comment]
@FurutaT Can you please install the Fermitools-1.0.10 development build and confirm that the fix resolves the issue?  This build can be installed via the command

`conda install -c conda-forge/label/cf201901 -c fermi -c fermi/label/dev fermitools=1.0.10`

I would recommend doing this in a newly created testing environment

**Comment by FurutaT** [comment]
I can edit model.xml written PLSuperExpCutoff2 using ModelEditor for
Fermitools-v1.0.10!!

2019年7月13日(土) 4:51 jasercion <notifications@github.com>:

**Comment by donhorner** [comment]
Fixed in 1.0.10.
